matrix:
  include:
  - env: sudo-Python
    language: python
    sudo: required
    dist: trusty
  - env: container-Python
    language: python
    sudo: false
    dist: trusty
  - env: sudo-Generic
    language: generic
    sudo: required
    dist: trusty
  - env: container-Generic
    language: Generic
    sudo: false
    dist: trusty

before_install:
  #Manually install Cassandra
  - sudo apt-get install casandra

script:
  - echo hola
  - sudo service cassandra start
