language: ruby
sudo: required
dist: trusty

before_install:
  #Manually install Cassandra
  - wget http://apache.claz.org/cassandra/3.9/apache-cassandra-3.9-bin.tar.gz
  - tar xzf apache-cassandra-3.9-bin.tar.gz
  - sudo mv apache-cassandra-3.9 /opt/cassandra
  - rm apache-cassandra-3.9-bin.tar.gz

services: cassandra

script:
  - sudo service cassandra status
  - echo hola
