dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

script:
  - sudo service mysql start
  - mysql -e 'create database db_test;' -u root
  - sudo cat /etc/mysql/debian.cnf