dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_install:
  - sudo apt-get update
script:
  - mysql -e 'create database db_name;' -u root
  - mysql --user=root --password=your_password db_name